export def 'from name' [] {
  match $in {
    "Live" => {":ableton:"}
    "Acrobat" => {":acrobat:"}
    "Activity Monitor" | "Aktivitätsanzeige" => {":activity_monitor:"}
    "Actual" => {":actual:"}
    "Adobe Bridge" => {":adobe_bridge:"}
    "AFFiNE" => {":affine:"}
    "Affinity Designer" => {":affinity_designer:"}
    "Affinity Designer 2" => {":affinity_designer_2:"}
    "Affinity Photo" => {":affinity_photo:"}
    "Affinity Photo 2" => {":affinity_photo_2:"}
    "Affinity Publisher" => {":affinity_publisher:"}
    "Affinity Publisher 2" => {":affinity_publisher_2:"}
    "Airmail" => {":airmail:"}
    "AirPort Utility" => {":airport_utility:"}
    "Alacritty" => {":alacritty:"}
    "Alfred" => {":alfred:"}
    "AltTab" => {":alttab:"}
    "AmneziaVPN" => {":amnezia_vpn:"}
    "Android Messages" => {":android_messages:"}
    "Android Studio" => {":android_studio:"}
    "Anki" => {":anki:"}
    "Anytype" => {":anytype:"}
    "Apifox" => {":apifox:"}
    "App Eraser" => {":app_eraser:"}
    "App Store" => {":app_store:"}
    "Books" | "Apple Books" => {":apple_books:"}
    "Arc" => {":arc:"}
    "Arduino" | "Arduino IDE" => {":arduino:"}
    "Atom" => {":atom:"}
    "Audacity" => {":audacity:"}
    "Automator" => {":automator:"}
    "balenaEtcher" => {":balena_etcher:"}
    "Bambu Studio" => {":bambu_studio:"}
    "MoneyMoney" => {":bank:"}
    "Battle.net" => {":battle_net:"}
    "Bazecor" => {":bazecor:"}
    "Bear" => {":bear:"}
    "BetterTouchTool" => {":bettertouchtool:"}
    "Bilibili" | "哔哩哔哩" => {":bilibili:"}
    "Bitwarden" => {":bit_warden:"}
    "Blender" => {":blender:"}
    "Blitzit" => {":blitzit:"}
    "Bluetooth File Exchange" => {":bluetooth_file_exchange:"}
    "BluOS Controller" => {":bluos_controller:"}
    "Books" | "Calibre" | "Bücher" => {":book:"}
    "Brain.fm" => {":brainfm:"}
    "Brave Browser" => {":brave_browser:"}
    "Bruno" => {":bruno:"}
    "Burp Suite" => {":burp_suite:"}
    "BusyCal" => {":busycal:"}
    "Calculator" | "Calculette" | "Rechner" => {":calculator:"}
    "Calendar" | "日历" | "Fantastical" | "Cron" | "Amie" | "Calendrier" | "カレンダー" | "Notion Calendar" | "Kalender" => {":calendar:"}
    "calibre" => {":calibre:"}
    "Capacities" => {":capacities:"}
    "Caprine" => {":caprine:"}
    "Amazon Chime" => {":chime:"}
    "Choosy" => {":choosy:"}
    "Cisco AnyConnect Secure Mobility Client" | "Cisco Secure Client" => {":cisco_anyconnect:"}
    "Citrix Workspace" | "Citrix Viewer" => {":citrix:"}
    "ClassIn" => {":classin:"}
    "Claude" => {":claude:"}
    "ClickUp" => {":click_up:"}
    "Clock" => {":clock:"}
    "coconutBattery" => {":coconut_battery:"}
    "Code" | "Code - Insiders" => {":code:"}
    "Cold Turkey Blocker" => {":cold_turkey_blocker:"}
    "Color Picker" | "数码测色计" => {":color_picker:"}
    "Comet" => {":comet:"}
    "Copilot" => {":copilot:"}
    "CotEditor" => {":coteditor:"}
    "Craft" => {":craft:"}
    "Creative Cloud" => {":creative_cloud:"}
    "Cursor" => {":cursor:"}
    "Cursor" => {":cursor_ide:"}
    "Cypress" => {":cypress:"}
    "Dash" => {":dash:"}
    "DataGrip" => {":datagrip:"}
    "DataSpell" => {":dataspell:"}
    "DaVinci Resolve" => {":davinciresolve:"}
    "DBeaver" => {":dbeaver:"}
    "DeepSeek" => {":deepseek:"}
    "Deezer" => {":deezer:"}
    "Default" => {":default:"}
    "deno" => {":deno:"}
    "CleanMyMac X" => {":desktop:"}
    "DEVONthink 3" => {":devonthink3:"}
    "Dexcom" => {":dexcom:"}
    "Dia" => {":dia:"}
    "DingTalk" | "钉钉" | "阿里钉" => {":dingtalk:"}
    "Discord" | "Discord Canary" | "Discord PTB" => {":discord:"}
    "Docker" | "Docker Desktop" => {":docker:"}
    "GrandTotal" | "Receipts" => {":dollar:"}
    "Double Commander" => {":doublecmd:"}
    "Downie 4" => {":downie:"}
    "Drafts" => {":drafts:"}
    "draw.io" => {":draw_io:"}
    "Dropbox" => {":dropbox:"}
    "Eagle" => {":eagle:"}
    "Element" => {":element:"}
    "Emacs" => {":emacs:"}
    "EuDic" => {":eudic:"}
    "Evernote Legacy" => {":evernote_legacy:"}
    "FaceTime" | "FaceTime 通话" => {":face_time:"}
    "Feishu" => {":feishu:"}
    "Figma" => {":figma:"}
    "Final Cut Pro" => {":final_cut_pro:"}
    "Find My" => {":find_my:"}
    "Finder" | "访达" => {":finder:"}
    "Firefox" => {":firefox:"}
    "Firefox Developer Edition" | "Firefox Nightly" => {":firefox_developer_edition:"}
    "FL Studio" => {":flstudio:"}
    "Folx" => {":folx:"}
    "Fork" => {":fork:"}
    "ForkLift" => {":forklift:"}
    "Foxit PDF Reader" => {":foxit_reader:"}
    "FreeCAD" => {":freecad:"}
    "Freeform" => {":freeform:"}
    "FreeTube" => {":freetube:"}
    "FSNotes" => {":fsnotes:"}
    "Fusion" => {":fusion:"}
    "Games" => {":games:"}
    "System Preferences" | "System Settings" | "系统设置" | "Réglages Système" | "システム設定" | "Systemeinstellungen" | "System­einstellungen" => {":gear:"}
    "Gemini" | "Google Gemini" => {":gemini:"}
    "Ghostty" => {":ghostty:"}
    "GIMP" => {":gimp:"}
    "GitHub Desktop" => {":git_hub:"}
    "Godot" => {":godot:"}
    "GoLand" => {":goland:"}
    "GoodLinks" => {":goodlinks:"}
    "Goodnotes" => {":goodnotes:"}
    "Google Chat" => {":google_chat:"}
    "Chromium" | "Google Chrome" | "Google Chrome Canary" => {":google_chrome:"}
    "Grammarly Editor" => {":grammarly:"}
    "Granola" => {":granola:"}
    "Grayjay" => {":grayjay:"}
    "Hammerspoon" => {":hammerspoon:"}
    "Hazel" => {":hazel:"}
    "Helium" => {":helium:"}
    "Home" => {":home:"}
    "Home Assistant" => {":home_assistant:"}
    "Hyper" => {":hyper:"}
    "IntelliJ IDEA" => {":idea:"}
    "IINA" => {":iina:"}
    "Adobe Illustrator" | "Illustrator" => {":illustrator:"}
    "Image Playground" => {":image_playground:"}
    "Adobe InDesign" | "InDesign" => {":indesign:"}
    "Infuse" => {":infuse:"}
    "Inkdrop" => {":inkdrop:"}
    "Inkscape" => {":inkscape:"}
    "Insomnia" => {":insomnia:"}
    "Instapaper" => {":instapaper:"}
    "iPhone Mirroring" => {":iphone_mirroring:"}
    "Iris" => {":iris:"}
    "iTerm" | "iTerm2" => {":iterm:"}
    "Jane Reader" => {":jane_reader:"}
    "Jellyfin Media Player" => {":jellyfin:"}
    "JetBrains Gateway" => {":jetbrains_gateway:"}
    "JetBrains Toolbox" => {":jetbrains_toolbox:"}
    "Joplin" => {":joplin:"}
    "Journal" => {":journal:"}
    "카카오톡" | "KakaoTalk" => {":kakaotalk:"}
    "Kakoune" => {":kakoune:"}
    "Karabiner-Elements Settings" => {":karabiner_elements:"}
    "Karabiner-EventViewer" => {":karabiner_elements_event_viewer:"}
    "KeePassXC" => {":kee_pass_x_c:"}
    "Keyboard Maestro" => {":keyboard_maestro:"}
    "Keynote" | "Keynote 讲演" => {":keynote:"}
    "KiCad" => {":kicad:"}
    "Kiro" => {":kiro:"}
    "kitty" => {":kitty:"}
    "Kodi" => {":kodi:"}
    "LanguageTool for Desktop" => {":languagetool_for_desktop:"}
    "League of Legends" => {":league_of_legends:"}
    "LibreWolf" => {":libre_wolf:"}
    "LibreOffice" => {":libreoffice:"}
    "Adobe Lightroom" => {":lightroom:"}
    "Lightroom Classic" => {":lightroomclassic:"}
    "LINE" => {":line:"}
    "Linear" => {":linear:"}
    "LM Studio" => {":lm_studio:"}
    "LocalSend" => {":localsend:"}
    "Logic Pro" => {":logicpro:"}
    "Logseq" => {":logseq:"}
    "Maccy" => {":maccy_clip:"}
    "MacPass" => {":macpass:"}
    "Canary Mail" | "HEY" | "Mail" | "Mailspring" | "MailMate" | "Superhuman" | "Spark" | "Spark Mail" | "邮件" | "メール" => {":mail:"}
    "MAMP" | "MAMP PRO" => {":mamp:"}
    "Maps" | "Google Maps" | "マップ" | "Karten" => {":maps:"}
    "Marked 2" => {":marked_2:"}
    "Marta" => {":marta:"}
    "Matlab" | "MATLAB" |"MATLABWindow" | "MATLAB_R2024b" | "MATLAB_R2024a" | "MATLAB_R2023b" | "MATLAB_R2023a" | "MATLAB_R2022b" | "MATLAB_R2022a" | "MATLAB_R2021b" | "MATLAB_R2021a" => {":matlab:"}
    "Mattermost" => {":mattermost:"}
    "Google Meet" => {":meet:"}
    "Messages" | "信息" | "Nachrichten" | "メッセージ" => {":messages:"}
    "Messenger" => {":messenger:"}
    "Microsoft Edge" => {":microsoft_edge:"}
    "Microsoft Excel" => {":microsoft_excel:"}
    "Microsoft Outlook" => {":microsoft_outlook:"}
    "Microsoft PowerPoint" => {":microsoft_power_point:"}
    "Microsoft Remote Desktop" => {":microsoft_remote_desktop:"}
    "Microsoft Teams" | "Microsoft Teams (work or school)" => {":microsoft_teams:"}
    "Microsoft Word" => {":microsoft_word:"}
    "Mimestream" => {":mimestream:"}
    "Min" => {":min_browser:"}
    "Miro" => {":miro:"}
    "MongoDB Compass" => {":mongodb:"}
    "Moonlight" => {":moonlight:"}
    "Movist Pro" => {":movist_pro:"}
    "mpv" => {":mpv:"}
    "Mullvad Browser" => {":mullvad_browser:"}
    "Music" | "音乐" | "Musique" | "ミュージック" | "Musik" | "Chromatix" => {":music:"}
    "Navicat Premium" => {":navicat:"}
    "Neovide" | "neovide" => {":neovide:"}
    "Neovim" | "neovim" | "nvim" => {":neovim:"}
    "网易云音乐" | "NetEaseMusic" => {":netease_music:"}
    "Netflix" => {":netflix:"}
    "NetNewsWire" => {":netnewswire:"}
    "News" => {":news:"}
    "Nextcloud" => {":nextcloud:"}
    "Nicotine+" => {":nicotine_plus:"}
    "Nimble Commander" | "NimbleCommander-Unsigned" => {":nimble_commander:"}
    "Noodl" | "Noodl Editor" => {":noodl:"}
    "NordVPN" => {":nord_vpn:"}
    "Notability" => {":notability:"}
    "Notes" | "备忘录" | "メモ" | "Notizen" => {":notes:"}
    "Notion" => {":notion:"}
    "Notion Mail" => {":notion_mail:"}
    "Nova" => {":nova:"}
    "Numbers" | "Numbers 表格" => {":numbers:"}
    "nvALT" => {":nvalt:"}
    "Nvidia GeForce Now" | "GeForceNOW" => {":nvidia_geforce_now:"}
    "Obsidian" => {":obsidian:"}
    "OBS" => {":obsstudio:"}
    "OmniFocus" => {":omni_focus:"}
    "1Password" => {":one_password:"}
    "Open Video Downloader" => {":open_video_downloader:"}
    "ChatGPT" => {":openai:"}
    "OpenAI Translator" => {":openai_translator:"}
    "OpenVPN Connect" => {":openvpn_connect:"}
    "Opera" => {":opera:"}
    "OrbStack" => {":orbstack:"}
    "OrcaSlicer" => {":orcaslicer:"}
    "Orion" | "Orion RC" => {":orion:"}
    "Overcast" => {":overcast:"}
    "Overleaf" | "ShareLaTeX" => {":overleaf:"}
    "Pages" | "Pages 文稿" => {":pages:"}
    "Parallels Desktop" => {":parallels:"}
    "Parcel" => {":parcel:"}
    "Parsec" => {":parsec:"}
    "Passepartout" => {":passepartout:"}
    "Passwords" | "Passwörter" => {":passwords:"}
    "PDF Expert" => {":pdf_expert:"}
    "Pearcleaner" => {":pearcleaner:"}
    "Perplexity" | "Perplexity AI" => {":perplexity:"}
    "Phoenix Slides" => {":phoenix_slides:"}
    "Phone" => {":phone:"}
    "Photos" | "Fotos" => {":photos:"}
    "Adobe Photoshop" => {":photoshop:"}
    "PhpStorm" => {":php_storm:"}
    "Pi-hole Remote" => {":pihole:"}
    "Pine" => {":pine:"}
    "Pixelmator Pro" => {":pixelmator_pro:"}
    "Play" => {":play:"}
    "Plex" => {":plex:"}
    "Plexamp" => {":plexamp:"}
    "Podcasts" | "播客" => {":podcasts:"}
    "PomoDone App" => {":pomodone:"}
    "Postman" => {":postman:"}
    "Premiere" | "Adobe Premiere" | "Adobe Premiere Pro 2024" => {":premiere:"}
    "Preview" | "预览" | "Skim" | "zathura" | "Aperçu" | "プレビュー" | "Vorschau" => {":preview:"}
    "Proton Mail" | "Proton Mail Bridge" => {":proton_mail:"}
    "Proton VPN" | "ProtonVPN" => {":proton_vpn:"}
    "PrusaSlicer" | "SuperSlicer" => {":prusaslicer:"}
    "PyCharm" => {":pycharm:"}
    "qBittorrent" => {":qbittorrent:"}
    "QLMarkdown" => {":qlmarkdown:"}
    "QQ" => {":qq:"}
    "QQ音乐" | "QQMusic" => {":qqmusic:"}
    "Quantumult X" => {":quantumult_x:"}
    "QuickTime Player" => {":quicktime:"}
    "Quip" => {":quip:"}
    "qutebrowser" => {":qute_browser:"}
    "Raindrop.io" => {":raindrop_io:"}
    "Raspberry Pi Imager" | "Raspberry Pi Connect" => {":raspberry_pi:"}
    "Raycast" => {":raycast:"}
    "Reeder" => {":reeder5:"}
    "rekordbox" => {":rekordbox:"}
    "Remind Faster" => {":remind_me_faster:"}
    "Reminders" | "提醒事项" | "Rappels" | "リマインダー" | "Erinnerungen" => {":reminders:"}
    "Replit" => {":replit:"}
    "Repo Prompt" => {":repo_prompt:"}
    "Rider" | "JetBrains Rider" => {":rider:"}
    "Rio" => {":rio:"}
    "Royal TSX" => {":royaltsx:"}
    "RustDesk" => {":rustdesk:"}
    "Safari" | "Safari浏览器" | "Safari Technology Preview" => {":safari:"}
    "Scribus" => {":scribus:"}
    "Seafile" => {":seafile:"}
    "Sequel Ace" => {":sequel_ace:"}
    "Sequel Pro" => {":sequel_pro:"}
    "Session" => {":session:"}
    "Setapp" => {":setapp:"}
    "SF Symbols" | "SF Symbole" | "SF-Symbole" => {":sf_symbols:"}
    "Shortcuts" => {":shortcuts:"}
    "Signal" => {":signal:"}
    "sioyek" => {":sioyek:"}
    "Sketch" => {":sketch:"}
    "Skype" => {":skype:"}
    "Slack" => {":slack:"}
    "SnippetsLab" => {":snippetslab:"}
    "solidtime" => {":solidtime:"}
    "Spark Desktop" => {":spark:"}
    "Spotify" => {":spotify:"}
    "Spotlight" => {":spotlight:"}
    "Steam" | "Steam Helper" => {":steam:"}
    "Studio 3T" => {":studio_3t:"}
    "Sublime Merge" => {":sublime_merge:"}
    "Sublime Text" => {":sublime_text:"}
    "Summoners War" => {":summoners_war:"}
    "superProductivity" => {":superproductivity:"}
    "Surfshark" => {":surfshark:"}
    "Swift Playground" => {":swift_playground:"}
    "T3 Chat" => {":t3chat:"}
    "Tabby" => {":tabby:"}
    "TablePlus" => {":tableplus:"}
    "Tana" => {":tana:"}
    "TeamSpeak 3" => {":team_speak:"}
    "Telegram" => {":telegram:"}
    "Terminal" | "终端" | "ターミナル" => {":terminal:"}
    "Termius" => {":termius:"}
    "Typora" => {":text:"}
    "TextEdit" => {":textedit:"}
    "Microsoft To Do" | "Things" => {":things:"}
    "Thunderbird" | "Thunderbird Daily" => {":thunderbird:"}
    "TickTick" => {":tick_tick:"}
    "TIDAL" => {":tidal:"}
    "Timery" => {":timery:"}
    "Tiny RDM" => {":tinyrdm:"}
    "Tips" => {":tips:"}
    "Todoist" => {":todoist:"}
    "Toggl Track" => {":toggl_track:"}
    "Tor Browser" => {":tor_browser:"}
    "Tot" => {":tot:"}
    "Tower" => {":tower:"}
    "TradingView" => {":trading_view:"}
    "Transmit" => {":transmit:"}
    "Trello" => {":trello:"}
    "TV" => {":tv:"}
    "Twingate" => {":twingate:"}
    "Tweetbot" | "Twitter" => {":twitter:"}
    "UTM" => {":utm:"}
    "VeraCrypt" => {":veracrypt:"}
    "MacVim" | "Vim" | "VimR" => {":vim:"}
    "Vivaldi" => {":vivaldi:"}
    "VLC" => {":vlc:"}
    "VMware Fusion" => {":vmware_fusion:"}
    "Voice Memos" => {":voice_memos:"}
    "Vorta" => {":vorta:"}
    "VSCodium" => {":vscodium:"}
    "Warp" => {":warp:"}
    "Weather" | "Wetter" => {":weather:"}
    "WebStorm" => {":web_storm:"}
    "Webull Desktop" => {":webull:"}
    "微信" | "WeChat" => {":wechat:"}
    "企业微信" | "WeCom" => {":wecom:"}
    "WezTerm" | "wezterm-gui" => {":wezterm:"}
    "WhatsApp" | "‎WhatsApp" => {":whats_app:"}
    "Windows App" => {":windows_app:"}
    "WireGuard" => {":wireguard:"}
    "Xcode" => {":xcode:"}
    "Yandex Browser"  | "Yandex Browser" | "Yandex" => {":yandex_bower:"}
    "Yandex Music" => {":yandex_music:"}
    "Yazi" | "yazi" => {":yazi:"}
    "YouTube" => {":youtube:"}
    "YouTube Music" => {":youtube_music:"}
    "Yuque" | "语雀" => {":yuque:"}
    "Zed" => {":zed:"}
    "Zen" | "Zen Browser" => {":zen_browser:"}
    "Zeplin" => {":zeplin:"}
    "zoom.us" => {":zoom:"}
    "Zotero" => {":zotero:"}
    "Zulip" => {":zulip:"}
    _ => { ":default:" }
  }
}
