[tools]
atuin = "18.13.3"
chezmoi = "2.70.0"
bat = "0.26.1"
helix = "25.07.1"
starship = "1.24.2"
vivid = "0.10.1"
zoxide = "0.9.9"
zellij = "0.43.1"
"github:topgrade-rs/topgrade" = "17.1.0"
lazygit = "0.60.0"
lazydocker = "0.25.0"
rust = "1.94.0"
"cargo:pueue" = "4.0.4"
delta = "0.18.2"
gh = "2.88.1"
"aqua:fish-shell/fish-shell" = "4.5.0"
carapace = "1.6.3"
"aqua:nushell/nushell" = "0.111.0"
"cargo:tlrc" = "latest"
