[tools]
atuin = "18.16.0"
chezmoi = "2.70.2"
bat = "0.26.1"
helix = "25.07.1"
starship = "1.25.1"
vivid = "0.11.1"
zoxide = "0.9.9"
zellij = "0.44.1"
"github:topgrade-rs/topgrade" = "17.4.0"
lazygit = "0.61.1"
lazydocker = "0.25.2"
rust = "1.95.0"
"cargo:pueue" = "4.0.4"
delta = "0.19.2"
gh = "2.92.0"
carapace = "1.6.5"
"aqua:nushell/nushell" = "0.112.2"
"cargo:tlrc" = "latest"
television = "0.15.6"
"aqua:fish-shell/fish-shell" = "4.6.0"
"github:asciimoo/hister" = "0.13.0"
